Styles by hanni
gin-fizz/styleguide pull request #9
Opened 2016-12-06 20:52 UTC by hannnegoossens

A completely new style for our site!

2016-12-06 20:55 UTC, Haroenv requested changes
Some changes. Overall good idea. Can you show some screenshots in the PR?

2016-12-06 20:55 UTC, Haroenv commented on _components/header.md
> +    <a href="/me"><img src="{{site.baseurl}}/src/img/userBlue.png" alt="me"></a>
Logo in svg

2016-12-06 20:55 UTC, Haroenv commented on _components/poll-input.md
> +  <input type="text" placeholder="Enter an option" name="optionXX">
No placeholders

2016-12-06 20:55 UTC, Haroenv commented on _sass/base.scss
> +  color: $green;
No named variables after what it is. Use what it's used for

2016-12-06 20:55 UTC, Haroenv commented on _sass/components/poll.scss
> +      display: none;
Terrible. Labels are visible

2016-12-06 20:55 UTC, Haroenv commented on _sass/variables.scss
> +$red-dark: #5C2828;
Don't make new variables. Reuse the old names

2016-12-06 21:00 UTC, hannnegoossens commented on _components/poll-input.md
> +  <input type="text" placeholder="Enter an option" name="optionXX">
Why not? Placeholders instead of labels?

2016-12-06 21:01 UTC, Haroenv commented on _components/poll-input.md
> +  <input type="text" placeholder="Enter an option" name="optionXX">
Bad user experience. Can't see what you're supposed to fill in without labels

2016-12-06 21:02 UTC, Haroenv commented on _components/poll-input.md
> +  <input type="text" placeholder="Enter an option" name="optionXX">
Can give a quote out of heydon's book if you need it

2016-12-06 21:20 UTC, hannnegoossens commented
![image](https://cloud.githubusercontent.com/assets/12141239/20943972/f50cafd0-bc01-11e6-87ac-79a9e7a351ac.png)

![image](https://cloud.githubusercontent.com/assets/12141239/20944000/15955d56-bc02-11e6-8c7e-3c755d55fd2c.png)

![image](https://cloud.githubusercontent.com/assets/12141239/20944015/2868c1e8-bc02-11e6-9d26-561924472d71.png)

2016-12-06 21:44 UTC, ArnaudWeyts commented
maak het minder cancer aub

2016-12-07 13:05 UTC, Haroenv commented on _components/header.md
> +  <a href="/"><img src="{{site.baseurl}}/src/img/logoBlue.svg" alt="home"></a>
change the fill colour in the svg itself. Don't make a new image 😄

2016-12-11 10:40 UTC, Haroenv commented
reference image now:

![](https://i.imgur.com/AuLoxvD.png)

2016-12-11 10:45 UTC, Haroenv approved these changes

2016-12-11 11:13 UTC, Haroenv commented on _components/header.md
>    <a href="/"><img src="{{site.baseurl}}/src/img/logo.svg" alt="home"></a>
Should have a way to log out and show the current user

2016-12-11 13:52 UTC, thysruben commented
<img width="968" alt="screenshot 2016-12-11 14 51 27" src="https://cloud.githubusercontent.com/assets/23338021/21080513/65554150-bfb1-11e6-900c-f7eb1495f674.png">

2016-12-11 14:28 UTC, merged

2016-12-12 20:27 UTC, hannnegoossens commented
@ArnaudWeyts, kenkerman, ist nu beter??

2016-12-12 20:31 UTC, ArnaudWeyts commented
@hannnegoossens Goed zo 😎